version: '3.9'

services:

  redis:
    image: redis:7-bullseye
    container_name: redis
    depends_on:
      - event_db

  redis_commander:
    container_name: redis_commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
    - "8082:8081"
    depends_on:
      - redis

  backend_event_handler:
    image: cosmonaut-cat/backend_event_handler:latest
    container_name: backend_event_handler
    depends_on:
      - event_db
      - read_db
      - redis
    env_file:
      - .env
    command: 
    - event_handler
  
  grpc_ui_event_handler:
    container_name: grpc_ui_event_handler
    image: fullstorydev/grpcui
    depends_on:
      - backend_event_handler
    ports:
      - 13030:8080
    command: 
      - -plaintext
      - -use-reflection
      - backend_event_handler:3030

  backend_front_api:
    image: cosmonaut-cat/backend_front_api:latest
    container_name: backend_front_api
    depends_on:
      - event_db
      - read_db
      - redis
      - backend_event_handler
    env_file:
      - .env
    command: 
    - front_api

  grpc_ui_front_api:
    container_name: grpc_ui_front_api
    image: fullstorydev/grpcui
    depends_on:
      - backend_front_api
    ports:
      - 13031:8080
    command: 
      - -plaintext
      - -use-reflection
      - backend_front_api:3031

  event_db:
    container_name: event_db
    image: mariadb
    command: 
     --binlog_format=row
     --server_id=230799
     --log_bin=mysql-bin
     --binlog_row_image=full
     --expire_logs_days=10
    restart: always
    volumes:
      - ./configs/event_db/sql/schema.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MARIADB_ROOT_PASSWORD: ${EVENT_DATABASE_PASS}

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - event_db
    restart: always
    ports:
      - 8080:8080

  read_db:
    container_name: read_db
    image: mongo
    restart: always
    volumes: 
      - ./configs/read_db/init_read_db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${READ_DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${READ_DATABASE_PASS}

  mongo_express:
    container_name: mongo_express
    image: mongo-express
    depends_on:
      - read_db
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${READ_DATABASE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${READ_DATABASE_PASS}
      # ME_CONFIG_MONGODB_URL: mongodb://${READ_DATABASE_USER}:${READ_DATABASE_PASS}@read_db:${READ_DATABASE_PORT}/
      ME_CONFIG_MONGODB_URL: ${READ_DATABASE_URI}

  debezium_server:
    container_name: debezium_server
    image: debezium/server
    volumes:
      - ./configs/debezium/conf:/debezium/conf
    ports:
      - 8083:8083
    depends_on:
      - read_db
      - redis
      - event_db